spring:
  profiles:
    active: dev
  application:
    name: news-service
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-master.yml
    default-schema: news
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: news
    open-in-view: false
server:
  port: ${SERVER_PORT:8090}
urls:
  userservice_url: http://localhost:8081/